### ISSUE TITLE
Onboarding overview component

### ISSUE THREAD

**Issue by Zueis** [RnDAO/tc-uiComm#113]
### Description:
We need to implement an Onboarding overview section based on a specific Figma URL.

### Tasks to Implement:
- [ ] Analyze UX/UI design in Figma and see the requirement.
- [ ] Implement UI design in code.
- [ ] Integrate UI with API.
- [ ] Write a unit test for it.

### References:
- Figma Design: [[Click here!](https://www.figma.com/file/whU3PlyPvdoSWdhUYQW7e9/Community-Health?type=design&node-id=243-1&t=qxWeumHa65KiyBQj-0)]

**Comment by Zueis** [comment]
@cyri113 yes this one is merged and available in the dev environment.
